#!/bin/bash

# Get the directory where this script is located
script_dir="$(dirname "$(realpath "$0")")"

# Change to the directory where the LaTeX files are located
cd figures/tikz

# Check if the cd command was successful
if [ $? -eq 0 ]; then
    echo "Now compiling LaTeX files in $(pwd)..."

    # Define the list of files to compile
    file_list=("p2x2p_system.tex" "figure_1.tex" "figure_2.tex" "figure_3.tex" "figure_4.tex" "figure_5.tex" "figure_6.tex" "mfrr_overview.tex")

    # Define the list of files not to copy (just the base names, without extensions)
    exclude_from_copy=("p2x2p_system")

    for file in "${file_list[@]}"; do
        if [[ -f "$file" ]]; then
            echo "Compiling $file..."
            pdflatex -interaction=batchmode "$file" > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                echo "$file compiled successfully."
                # Remove non-PDF files generated by pdflatex
                base_name="${file%.tex}"
                rm -f "$base_name".aux "$base_name".log "$base_name".toc "$base_name".out "$base_name".nav "$base_name".snm "$base_name".bbl "$base_name".blg

                # Check if the file should be excluded from copying
                if [[ ! " ${exclude_from_copy[@]} " =~ " $base_name " ]]; then
                    # Copy the generated PDF to the script directory
                    if [[ -f "$base_name.pdf" ]]; then
                        mv "$base_name.pdf" "$script_dir"
                        echo "$base_name.pdf copied to $script_dir."
                    else
                        echo "Error: $base_name.pdf not found."
                    fi
                else
                    echo "Skipping copy of $base_name.pdf (in exclude list)."
                fi
            else
                echo "Error compiling $file."
            fi
        else
            echo "Warning: $file does not exist in the directory."
        fi
    done
else
    echo "Error: Could not change to the desired directory."
    exit 1
fi

