#!/bin/bash

# Change to the directory where the LaTeX files are located
cd figures/tikz

# Check if the cd command was successful
if [ $? -eq 0 ]; then
    echo "Now compiling LaTeX files in $(pwd)..."

    # Define the list of files to compile
    file_list=("p2x2p_system.tex" "figure_1.tex" "figure_2.tex" "figure_3.tex" "figure_4.tex" "figure_5.tex" "figure_6.tex" "mfrr_overview.tex")  # Replace with your filenames

    for file in "${file_list[@]}"; do
        if [[ -f "$file" ]]; then
            echo "Compiling $file..."
            pdflatex -interaction=batchmode "$file" > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                echo "$file compiled successfully."
                # Remove non-PDF files generated by pdflatex
                base_name="${file%.tex}"
                rm -f "$base_name".aux "$base_name".log "$base_name".toc "$base_name".out "$base_name".nav "$base_name".snm "$base_name".bbl "$base_name".blg
            else
                echo "Error compiling $file."
            fi
        else
            echo "Warning: $file does not exist in the directory."
        fi
    done
else
    echo "Error: Could not change to the desired directory."
    exit 1
fi

